sudo: false

language: python

cache:
  directories:
  - $HOME/env

notifications:
  email: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
    - sox

before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment

# command to install dependencies
install:
  - pip install coveralls
  - pip install git+https://github.com/librosa/librosa.git
  - pip install -e .
  - pip install mock

# command to run tests
script: nosetests --with-coverage --cover-erase --cover-package=massage -v -w tests/

after_success:
    - coveralls
    - pip uninstall -y massage

after_failure:
    - pip uninstall -y massage
